platform :ios, '8.0'
use_frameworks!

def testing_pods
  # pod 'Quick', "~> 0.9.0"
  # pod 'Nimble', "~> 3.2.0"
end

target 'Touch2Buy' do
  pod 'ActionSheetPicker-3.0',"~> 2.0.5"
  pod 'ChameleonFramework',"~> 2.1.0"
  pod 'CHTCollectionViewWaterfallLayout',"~> 0.9.2"
  pod 'DropDown',"~> 0.1.4"
  pod 'Google/Analytics'
  pod 'Kingfisher',"~> 1.8.3"
  pod 'MIBadgeButton-Swift',"~> 0.3"
  pod 'MZFormSheetPresentationController',"~> 2.3.2"
  pod 'PageMenu',"~>1.2.9"
  pod 'PagingMenuController',"~> 1.1.2"
  pod 'RMDateSelectionViewController',"~> 2.0.3"
  pod 'SCLAlertView',"~> 0.4.3"
  pod 'SwiftyJSON',"~> 2.3.2"
end

target 'Touch2BuyTests' do
    testing_pods
end

target 'Touch2BuyUITests' do
    testing_pods
end
